// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkHdMnwyZKTW6byZqG43yH7xMjVRLjYhI',
    appId: '1:44988924524:web:19b913c95851fed3d98e49',
    messagingSenderId: '44988924524',
    projectId: 'lensify-41e8b',
    authDomain: 'lensify-41e8b.firebaseapp.com',
    storageBucket: 'lensify-41e8b.firebasestorage.app',
    measurementId: 'G-M850JSR866',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCueyZBVzx0NDT5wk1Us96N3dG55YpvwCg',
    appId: '1:44988924524:android:e407069d47f73ed7d98e49',
    messagingSenderId: '44988924524',
    projectId: 'lensify-41e8b',
    storageBucket: 'lensify-41e8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcqUVFsRI-EUS6hu4-btYc_EL3usJ6n_A',
    appId: '1:44988924524:ios:7ca08fa9574fb5c4d98e49',
    messagingSenderId: '44988924524',
    projectId: 'lensify-41e8b',
    storageBucket: 'lensify-41e8b.firebasestorage.app',
    iosBundleId: 'com.example.lenscart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcqUVFsRI-EUS6hu4-btYc_EL3usJ6n_A',
    appId: '1:44988924524:ios:7ca08fa9574fb5c4d98e49',
    messagingSenderId: '44988924524',
    projectId: 'lensify-41e8b',
    storageBucket: 'lensify-41e8b.firebasestorage.app',
    iosBundleId: 'com.example.lenscart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkHdMnwyZKTW6byZqG43yH7xMjVRLjYhI',
    appId: '1:44988924524:web:4059ada6e2b3842bd98e49',
    messagingSenderId: '44988924524',
    projectId: 'lensify-41e8b',
    authDomain: 'lensify-41e8b.firebaseapp.com',
    storageBucket: 'lensify-41e8b.firebasestorage.app',
    measurementId: 'G-NSKLJGD819',
  );
}
